namespace: finallycoffee
name: nextcloud
version: "0.8.1"
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Installing and configuring nextcloud (and related apps/services) using docker
dependencies:
  "community.docker": "^4.6.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/nextcloud
issues: https://codeberg.org/finallycoffee/ansible-collection-nextcloud/issues
tags:
  - nextcloud
  - nextcloud_apps
  - docker
