namespace: finallycoffee
name: nextcloud
version: 0.6.0
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Installing and configuring nextcloud (and related apps/services) using docker
dependencies:
  "community.docker": "^1.10.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/nextcloud
issues: https://git.finally.coffee/finallycoffee/nextcloud/issues
