---

nextcloud_version: 30.0.1
nextcloud_user: nextcloud
nextcloud_basepath: /opt/nextcloud
nextcloud_config_path: "{{ nextcloud_basepath }}/config"
# Where data from nextcloud like apps etc are persisted
nextcloud_data_path: "{{ nextcloud_basepath }}/data"
# Where user data like media, documents etc are persisted
nextcloud_storage_path: "{{ nextcloud_basepath }}/storage"
nextcloud_fpm_config_path: "{{ nextcloud_basepath }}/fpm-config"
#nextcloud_socket_path: "{{ nextcloud_basepath }}/socket"

nextcloud_background_job_mode: cron

nextcloud_database_type: sqlite
nextcloud_database_name: nextcloud
nextcloud_database_user: nextcloud
nextcloud_database_pass: ~
nextcloud_database_host: localhost

nextcloud_container_name: nextcloud
nextcloud_container_image_server: docker.io
nextcloud_container_image_namespace: library
nextcloud_container_image_name: nextcloud
nextcloud_container_image: >-2
  {{
    [
      nextcloud_container_image_server,
      nextcloud_container_image_namespace,
      nextcloud_container_image_name,
    ] | join('/')
  }}
nextcloud_container_image_variant: "-fpm-alpine"
nextcloud_container_image_ref: >-2
  {{ nextcloud_container_image }}:{{ nextcloud_version }}{{ nextcloud_container_image_variant }}
nextcloud_container_image_force_source: false
nextcloud_container_restart_policy: "unless-stopped"

# in defaults so it can be unset if needed
nextcloud_container_base_volumes:
  - "{{ nextcloud_config_path }}:/var/www/html/config:z"
  - "{{ nextcloud_storage_path }}:/var/www/html/data:z"
  - "{{ nextcloud_data_path }}:/var/www/html:z"
  - "{{ nextcloud_fpm_config_path }}/opcache.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:z"
  - "{{ nextcloud_fpm_config_path }}/fpm.ini:/usr/local/etc/php-fpm.d/www.conf:z"
  - "{{ nextcloud_fpm_config_path }}/fpm-docker.ini:/usr/local/etc/php-fpm.d/zz-docker.conf:z"
  - "{{ nextcloud_basepath }}/nextcloud-passwd:/etc/passwd:z"
  - "{{ nextcloud_basepath }}/nextcloud-group:/etc/group:z"
nextcloud_container_extra_volumes: []
nextcloud_container_extra_labels: {}
nextcloud_container_extra_environment: {}

nextcloud_container_networks: ~
nextcloud_container_purge_other_networks: true

nextcloud_paths:
  - path: "{{ nextcloud_config_path }}"
    mode: "0755"
    owner: "{{ nextcloud_user_info.uid | default(nextcloud_user) }}"
    group: root
  - path: "{{ nextcloud_data_path }}"
    mode: "0755"
    owner: "{{ nextcloud_user_info.uid | default(nextcloud_user) }}"
    group: "{{ nextcloud_user_info.group | default(nextcloud_user) }}"
  - path: "{{ nextcloud_fpm_config_path }}"
    mode: "0750"
    owner: root
    group: root
  - path: "{{ nextcloud_storage_path }}"
    mode: "0770"
    owner: "{{ nextcloud_user_info.uid | default(nextcloud_user) }}"
    group: "root"

# PHP OpCache tuning
nextcloud_opcache_enable: 1
nextcloud_opcache_interned_strings_buffer_mb: 32
nextcloud_opcache_max_accelerated_files: 32531
nextcloud_opcache_memory_consumption_mb: 256
nextcloud_opcache_fast_shutdown: 1
nextcloud_opcache_save_comments: 1
nextcloud_opcache_revalidate_freq: 1
nextcloud_opcache_validate_timestamps: 0

# FPM config
nextcloud_fpm_max_children: 64
nextcloud_fpm_start_servers: "{{ nextcloud_fpm_max_children / 2 | int }}"
nextcloud_fpm_min_spare_servers: "{{ nextcloud_fpm_max_children / 4 | int }}"
nextcloud_fpm_max_spare_servers: "{{ nextcloud_fpm_max_children * 3/4 | int }}"

nextcloud_php_memory_limit: 1024M
nextcloud_php_upload_limit: 1024M
