---

nc_ldap_api_path: "/ocs/v2.php/apps/user_ldap/api/v1/config"
nc_ldap_api_url: "{{ nc_ldap_api_instance_url }}{{ nc_ldap_api_path }}"
nc_ldap_api_headers:
  OCS-APIREQUEST: "true"
nc_ldap_api_parameter_format: json

nc_ldap_config_keys:
  ldapHost: "{{ nc_ldap_config_host }}"
  ldapPort: "{{ nc_ldap_config_port }}"
  ldapBackupHost: "{{ nc_ldap_config_backup_host }}"
  ldapBackupPort: "{{ nc_ldap_config_backup_port }}"
  ldapOverrideMainServer: "{{ nc_ldap_config_override_main_server }}"
  ldapBase: "{{ nc_ldap_config_base_dn }}"
  ldapBaseUsers: "{{ nc_ldap_config_base_dn_users }}"
  ldapBaseGroups: "{{ nc_ldap_config_base_dn_groups }}"
  ldapAgentName: "{{ nc_ldap_config_agent_name }}"
  ldapAgentPassword: "{{ nc_ldap_config_agent_password }}"
  ldapTLS: "{{ nc_ldap_config_tls }}"
  turnOffCertCheck: "{{ nc_ldap_config_turn_off_cert_check }}"
  ldapUserDisplayName: "{{ nc_ldap_config_user_displayname }}"
  ldapUserDisplayName2: "{{ nc_ldap_config_user_displayname2 }}"
  ldapUserAvatarRule: "{{ nc_ldap_config_user_avatar_rule }}"
  ldapGidNumber: "{{ nc_ldap_config_gid_number }}"
  ldapUserFilterObjectclass: "{{ nc_ldap_config_user_filter_objectclass }}"
  ldapUserFilterGroups: "{{ nc_ldap_config_user_filter_groups }}"
  ldapUserFilter: "{{ nc_ldap_config_user_filter }}"
  ldapUserFilterMode: "{{ nc_ldap_config_user_filter_mode }}"
  ldapAttributesForUserSearch: "{{ nc_ldap_config_attributes_for_user_search }}"
  ldapGroupFilter: "{{ nc_ldap_config_group_filter }}"
  ldapGroupFilterMode: "{{ nc_ldap_config_group_filter_mode }}"
  ldapGroupFilterObjectclass: "{{ nc_ldap_config_group_filter_objectclass }}"
  ldapGroupFilterGroups: "{{ nc_ldap_config_group_filter_groups }}"
  ldapGroupMemberAssocAttr: "{{ nc_ldap_config_group_member_assoc_attr }}"
  ldapGroupDisplayName: "{{ nc_ldap_config_group_displayname }}"
  ldapAttributesForGroupSearch: "{{ nc_ldap_config_attributes_for_group_search }}"
  ldapLoginFilter: "{{ nc_ldap_config_login_filter }}"
  ldapLoginFilterMode: "{{ nc_ldap_config_login_filter_mode }}"
  ldapLoginFilterEmail: "{{ nc_ldap_config_login_filter_email }}"
  ldapLoginFilterUsername: "{{ nc_ldap_config_login_filter_username }}"
  ldapLoginFilterAttributes: "{{ nc_ldap_config_login_filter_attributes }}"
  ldapQuotaAttribute: "{{ nc_ldap_config_quota_attribute }}"
  ldapQuotaDefault: "{{ nc_ldap_config_quota_default }}"
  ldapEmailAttribute: "{{ nc_ldap_config_email_attribute }}"
  ldapCacheTTL: "{{ nc_ldap_config_cache_ttl }}"
  ldapConfigurationActive: "{{ nc_ldap_config_configuration_active }}"
  ldapExperiencedAdmin: "{{ nc_ldap_config_experienced_admin }}"
  homeFolderNamingRule: "{{ nc_ldap_config_home_folder_naming_rule }}"
  useMemberOfToDetectMembership: "{{ nc_ldap_config_use_memberOf_to_detect_membership }}"
  ldapExpertUsernameAttr: "{{ nc_ldap_config_expert_username_attr }}"
  ldapExpertUUIDUserAttr: "{{ nc_ldap_config_expert_uuid_user_attr }}"
  ldapExpertUUIDGroupAttr: "{{ nc_ldap_config_expert_uuid_group_attr }}"
  ldapNestedGroups: "{{ nc_ldap_config_nested_groups }}"
  ldapPagingSize: "{{ nc_ldap_config_paging_size }}"
  turnOnPasswordChange: "{{ nc_ldap_config_turn_on_password_change }}"
  ldapDynamicGroupMemberURL: "{{ nc_ldap_config_dynamic_group_member_url }}"
  ldapDefaultPPolicyDN: "{{ nc_ldap_config_default_ppolicy_dn }}"

nc_ldap_config_changeset: {}
