---
- name: Ensure container image '{{ onlyoffice_documentserver_container_image }}' is {{ onlyoffice_documentserver_state }}
  community.docker.docker_image:
    name: "{{ onlyoffice_documentserver_container_image }}"
    state: "{{ onlyoffice_documentserver_state }}"
    source: "{{ onlyoffice_documentserver_container_image_source }}"
    force_source: "{{ onlyoffice_documentserver_container_image_force_source }}"

- name: Ensure container '{{ onlyoffice_documentserver_container_name }}' is {{ onlyoffice_documentserver_container_state }}
  community.docker.docker_container:
    name: "{{ onlyoffice_documentserver_container_name }}"
    image: "{{ onlyoffice_documentserver_container_image }}"
    env: "{{ onlyoffice_documentserver_container_env | default(omit, true) }}"
    ports: "{{ onlyoffice_documentserver_container_ports | default(omit, true) }}"
    labels: "{{ onlyoffice_documentserver_container_labels | default(omit, true) }}"
    volumes: "{{ onlyoffice_documentserver_all_volumes }}"
    ulimits: "{{ onlyoffice_documentserver_container_ulimits | default(omit, true) }}"
    networks: "{{ onlyoffice_documentserver_container_networks | default(omit, true) }}"
    dns_servers: "{{ onlyoffice_documentserver_container_dns_servers | default(omit, true) }}"
    etc_hosts: "{{ onlyoffice_documentserver_container_etc_hosts | default(omit, true) }}"
    memory: "{{ onlyoffice_documentserver_container_memory | default(omit, true) }}"
    memory_reservation: "{{ onlyoffice_documentserver_container_memory_reservation | default(omit, true) }}"
    memory_swap: "{{ onlyoffice_documentserver_container_memory_swap | default(omit, true) }}"
    restart_policy: "{{ onlyoffice_documentserver_container_restart_policy }}"
    state: "{{ onlyoffice_documentserver_container_state }}"
