---
- name: Ensure 'onlyoffice_documentserver_state' is valid
  ansible.builtin.fail:
    msg: >-2
      Unsupported state '{{ onlyoffice_documentserver_state }}'.
      Supported states are {{ onlyoffice_documentserver_states | join(', ') }}.
  when: onlyoffice_documentserver_state not in onlyoffice_documentserver_states

- name: Ensure 'onlyoffice_documentserver_deployment_method' is valid
  ansible.builtin.fail:
    msg: >-2
      Unsupported deployment method '{{ onlyoffice_documentserver_deployment_method }}'.
      Supported deployment methods are {{ onlyoffice_documentserver_deployment_methods | join(', ') }}.
  when: onlyoffice_documentserver_deployment_method not in onlyoffice_documentserver_deployment_methods

- name: Deploy using {{ onlyoffice_documentserver_deployment_method }}
  ansible.builtin.include_tasks:
    file: "deploy-{{ onlyoffice_documentserver_deployment_method }}.yml"
